### ISSUE TITLE
Add a comparison with Howler.js

### ISSUE THREAD

**Issue by jay-jlm** [afkcodes/audio_x#32]
Thanks for sharing it.
It would be great if a comparison with Howler.js was provided.

**Comment by afkcodes** [comment]
Hey @jay-jlm  Thanks for raising this, surely i will look into Howler.js and try to update the readme. Please let me know if you have any issues in with audio_x.

**Comment by afkcodes** [comment]
hello @jay-jlm i have been dealing with something so couldn't update the comparison, if you would like to take up and create a PR that would be awesome. It will take sometime for me.
